# Generated by Django 3.2.13 on 2023-02-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('matricule', models.CharField(blank=True, max_length=30)),
                ('civilite', models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Non defini', 'Non defini')], max_length=20)),
                ('photo', models.ImageField(blank=True, default='avatar.jpg', upload_to='entrepreneur_avatars')),
                ('telephone', models.CharField(blank=True, max_length=10)),
                ('structure', models.CharField(choices=[('Impulsions', 'Impulsions'), ('Eclosion', 'Eclosions')], max_length=40)),
                ('email', models.CharField(max_length=150)),
                ('nationalite', models.CharField(max_length=150)),
                ('naissance', models.CharField(max_length=100, verbose_name='pays de naissance')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='numero de telephone professionel')),
                ('adresse_postal', models.CharField(max_length=200)),
                ('securite_social', models.CharField(blank=True, max_length=240)),
                ('date_naissance', models.DateField()),
                ('ville', models.CharField(blank=True, max_length=120, verbose_name='lieu de residence')),
            ],
        ),
    ]
