# Generated by Django 3.2.13 on 2023-03-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30, verbose_name='prénom')),
                ('matricule', models.CharField(blank=True, max_length=30)),
                ('photo', models.ImageField(blank=True, default='avatar.jpg', upload_to='entrepreneur_avatars')),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='téléphone')),
                ('structure', models.CharField(choices=[('Impulsions', 'Impulsions'), ('Eclosion', 'Eclosions')], max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('nationalite', models.CharField(max_length=150, verbose_name='nationalité')),
                ('naissance', models.CharField(max_length=100, verbose_name='pays de naissance')),
                ('numero', models.CharField(blank=True, max_length=15, verbose_name='numéro de téléphone professionel')),
                ('adresse_postal', models.CharField(max_length=200, verbose_name='Code')),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('securite_social', models.CharField(blank=True, max_length=240, verbose_name=' Numéro de sécurité social')),
                ('date_naissance', models.DateField(verbose_name='date de naissance')),
                ('ville', models.CharField(blank=True, max_length=120, verbose_name='lieu de résidence')),
                ('fonction', models.CharField(blank=True, max_length=240)),
                ('date_entree', models.DateField(blank=True, null=True, verbose_name="date d'entrée dans la CAE")),
                ('debut', models.DateField(blank=True, null=True, verbose_name='date du début du contrat')),
                ('motif', models.CharField(blank=True, choices=[('CDI', 'Contrat à duree indéterminée'), ('CDD', 'Contrat à duree determinée'), ('Apprentissage', 'Apprentissage'), ('Professionalisation', 'Contrat de Professionalisation')], max_length=240, verbose_name=' Contrat de travail')),
                ('activite', models.CharField(blank=True, choices=[('Temps Plein', 'Temps Plein'), ('Temps Partiel', 'Temps Partiel'), ('Autre', 'Autre')], max_length=40, verbose_name='type de activité')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='fichiers/')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('nature', models.CharField(blank=True, choices=[('RV conseil', 'Rendez-vous conseil'), ('RV gestion', ' Rendez-vous gestion'), ('RV admin', ' Rendez-vous admin'), ('RV RH', 'Rendez vous RH'), ('RV compta', 'Rendez-vous comptabilité'), ('RV hebdo', ' Rendez-vous hebdomadaire')], max_length=240, verbose_name=' Nature du rendez vous')),
                ('lieu', models.CharField(blank=True, choices=[('presentiel', 'Presentiel'), ('a distance', 'A distance')], max_length=100, verbose_name="Mode d'entretien")),
                ('objectifs', models.TextField(blank=True)),
                ('points', models.TextField(max_length=1000, verbose_name='point qui ont été abordés')),
                ('notes', models.TextField(blank=True)),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflux.entrepreneur')),
            ],
        ),
    ]
