# Generated by Django 3.2.13 on 2023-02-14 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appflux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='activite',
            field=models.CharField(blank=True, choices=[('Temps Plein', 'Temps Plein'), ('Temps Partiel', 'Temps Partiel'), ('Autre', 'Autre')], max_length=40, verbose_name='type de activité'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='date_entree',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='debut',
            field=models.DateField(blank=True, null=True, verbose_name='date du debut du contrat'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='fonction',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='motif',
            field=models.CharField(blank=True, choices=[('CDI', 'Contrat à duree indéterminée'), ('CDD', 'Contrat à duree determinée'), ('Apprentissage', 'Apprentissage'), ('Professionalisation', 'Contrat de Professionalisation')], max_length=240, verbose_name=' Contrat de travail'),
        ),
    ]
