# Generated by Django 3.2.13 on 2023-02-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0002_auto_20230214_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='date_entree',
            field=models.DateField(blank=True, null=True, verbose_name="date d'entree dans la CAE"),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='date_naissance',
            field=models.DateField(verbose_name='date de naissance'),
        ),
    ]
