# Generated by Django 3.2.13 on 2023-03-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='points',
            field=models.TextField(blank=True, max_length=1000, verbose_name='point qui ont été abordés'),
        ),
    ]
