# Generated by Django 3.2.13 on 2023-02-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0002_entrepreneur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='naissance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='pays de naissance'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='nationalite',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='numero de telephone professionel'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='structure',
            field=models.CharField(blank=True, choices=[('Impulsions', 'Impulsions'), ('Eclosion', 'Eclosions')], max_length=40, null=True),
        ),
    ]
