# Generated by Django 3.2.13 on 2023-03-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0003_alter_rendezvous_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='nature',
            field=models.CharField(blank=True, choices=[('RDV conseil', 'Rendez-vous conseil'), ('RDV gestion', ' Rendez-vous gestion'), ('RDV administration', ' Rendez-vous admin'), ('RDV Ressources Humaines', 'Rendez vous RH'), ('RDV comptabilité', 'Rendez-vous comptabilité'), ('RDV hebdomadaire', ' Rendez-vous hebdomadaire')], max_length=240, verbose_name=' Nature du rendez vous'),
        ),
    ]
