# Generated by Django 3.2.13 on 2023-02-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0003_auto_20230213_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='adresse_postal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='securite_social',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='ville',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='lieu de residence'),
        ),
    ]
