# Generated by Django 3.2.13 on 2023-02-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0003_auto_20230214_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='numero',
            field=models.CharField(blank=True, max_length=15, verbose_name='numero de telephone professionel'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
