# Generated by Django 3.2.13 on 2023-03-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0004_alter_rendezvous_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='points',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Point qui ont été abordés'),
        ),
    ]
