# Generated by Django 3.2.13 on 2023-02-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0005_alter_entrepreneur_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneur',
            name='civilite',
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
