# Generated by Django 3.2.13 on 2023-02-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0006_auto_20230215_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='adresse_postal',
            field=models.CharField(max_length=200, verbose_name='Code Postal'),
        ),
    ]
