# Generated by Django 3.2.13 on 2023-03-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0006_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='heure',
            field=models.TimeField(),
        ),
    ]
