# Generated by Django 3.2.13 on 2023-02-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0007_alter_entrepreneur_adresse_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='adresse_postal',
            field=models.CharField(max_length=200, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='date_entree',
            field=models.DateField(blank=True, null=True, verbose_name="date d'entrée dans la CAE"),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='debut',
            field=models.DateField(blank=True, null=True, verbose_name='date du début du contrat'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='nationalite',
            field=models.CharField(max_length=150, verbose_name='nationalité'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='numero',
            field=models.CharField(blank=True, max_length=15, verbose_name='numéro de téléphone professionel'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='prenom',
            field=models.CharField(max_length=30, verbose_name='prenom'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='securite_social',
            field=models.CharField(blank=True, max_length=240, verbose_name=' numero de securité social'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='téléphone'),
        ),
    ]
