# Generated by Django 3.2.13 on 2023-03-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0008_alter_evenement_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='sujet',
            field=models.CharField(max_length=20),
        ),
    ]
