# Generated by Django 3.2.13 on 2023-02-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0009_alter_entrepreneur_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='securite_social',
            field=models.CharField(blank=True, max_length=240, verbose_name=' Numero de sécurité social'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='ville',
            field=models.CharField(blank=True, max_length=120, verbose_name='lieu de résidence'),
        ),
    ]
