# Generated by Django 3.2.13 on 2023-03-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0010_answer_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
