# Generated by Django 3.2.13 on 2023-02-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0010_auto_20230215_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='securite_social',
            field=models.CharField(blank=True, max_length=240, verbose_name=' Numéro de sécurité social'),
        ),
    ]
