# Generated by Django 3.2.13 on 2023-02-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0011_alter_entrepreneur_securite_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='attestation',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='dispense de mutuel'),
        ),
    ]
