# Generated by Django 3.2.13 on 2023-02-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0012_entrepreneur_attestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneur',
            name='attestation',
        ),
    ]
