# Generated by Django 3.2.13 on 2023-03-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0013_auto_20230320_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='conjoint_mutuelle',
            field=models.BooleanField(blank=True, null=True, verbose_name='Avez vous un conjoint qui a soucris a la mutuelle ?'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='date_mutuelle',
            field=models.DateField(blank=True, null=True, verbose_name='Date pour la mutuelle'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='dispense',
            field=models.BooleanField(blank=True, null=True, verbose_name="Avez vous une dispense pour l'affiliation"),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='options',
            field=models.CharField(blank=True, choices=[('BASE', 'BASE'), ('BASE+1', 'BASE+1'), ('BASE+2', 'BASE+2'), ('BASE+3', 'BASE+3')], max_length=100, null=True),
        ),
    ]
