# Generated by Django 3.2.13 on 2023-04-17 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appflux', '0014_auto_20230320_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='lieu',
            field=models.CharField(blank=True, choices=[('presentiel', 'Presentiel'), ('a distance', 'A distance'), ('télephonique', 'Télephonique')], max_length=100, verbose_name="Mode d'entretien"),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Interlocuteur'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='points',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Points abordés'),
        ),
    ]
