# Generated by Django 3.2.13 on 2023-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0016_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
