# Generated by Django 3.2.13 on 2023-03-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appflux', '0018_alter_entrepreneur_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflux.entrepreneur')),
            ],
        ),
    ]
